import express from 'express';
import dotenv from 'dotenv';
import cors from 'cors';
import helmet from 'helmet';
import morgan from 'morgan';
import rateLimit from 'express-rate-limit';
import { connectDB } from './config/db.js';
import authRoutes from './routes/authRoutes.js';
import employeeRoutes from './routes/employeeRoutes.js';
import attendanceRoutes from './routes/attendanceRoutes.js';
import leaveRoutes from './routes/leaveRoutes.js';
import payrollRoutes from './routes/payrollRoutes.js';
import reportRoutes from './routes/reportRoutes.js';

dotenv.config();
connectDB();
const app = express();
app.use(helmet());
app.use(cors({ origin: process.env.CLIENT_URL?.split(',') || '*', credentials: true }));
app.use(express.json({ limit: '2mb' }));
app.use(morgan('dev'));
app.use(rateLimit({ windowMs: 15*60*1000, max: 300 }));
app.get('/', (req,res)=>res.json({ message:'RiseHR Pro API Running', version:'1.0.0' }));
app.get('/api/health', (req,res)=>res.json({ status:'ok', uptime:process.uptime() }));
app.use('/api/auth', authRoutes);
app.use('/api/employees', employeeRoutes);
app.use('/api/attendance', attendanceRoutes);
app.use('/api/leaves', leaveRoutes);
app.use('/api/payroll', payrollRoutes);
app.use('/api/reports', reportRoutes);
app.use((err, req, res, next)=> res.status(500).json({ message: err.message || 'Server error' }));
const PORT = process.env.PORT || 5000;
app.listen(PORT, '0.0.0.0', ()=> console.log(`Server running on port ${PORT}`));
